export const DARK_MODE = 'DARK_MODE';
export const ADD_TO_CART = 'ADD_TO_CART';
export const REMOVE_FROM_CART = 'REMOVE_FROM_CART';
export const STORE_TABLE_ITEM = 'STORE_TABLE_ITEM';
export const SEARCH_QUERY = 'SEARCH_QUERY';
export const TOGGLE_SEARCH_BOX = 'TOGGLE_SEARCH_BOX';
export const RESET_APP_STATE = 'RESET_APP_STATE';